### PR TITLE
chore(deps): bump k8s.io/kops from 1.29.2 to 1.30.0 (with generated code)

### PR DESCRIPTION
**Pull request by argoyle**
Bumps [k8s.io/kops](https://github.com/kubernetes/kops) from 1.29.2 to 1.30.0.
- [Release notes](https://github.com/kubernetes/kops/releases)
- [Commits](https://github.com/kubernetes/kops/compare/v1.29.2...v1.30.0)

---
updated-dependencies:
- dependency-name: k8s.io/kops dependency-type: direct:production update-type: version-update:semver-minor ...

### CODE REVIEW

**Comment by sl1pm4t** [comment]
Oh, the Github checks only run when the merge target is `main`.

**Comment by argoyle** [comment]
Hah, didn't even notice that it was set to merge back to the dependabot branch. 😂🙈

**Comment by argoyle** [comment]
Hmmm, compile errors, did I only do the generation 🤦🏻‍♂️ Another PR coming up.

**Comment by argoyle** [comment]
This one then (towards main this time): https://github.com/terraform-kops/terraform-provider-kops/pull/119

**Pull request merged**
