### PR TITLE
add GossipConfig & DNSControllerGossipConfig

### LINKED ISSUE #46: Add GossipConfig & DNSControllerGossipConfig cluster spec blocks
For deployments that use the Gossip based DNS, kops currently runs two gossip configurations in parallel:
- `mesh` (primary)
- `memberlistmesh` (secondary)

The intent was to allow the deprecated `mesh` gossip protocol to be phased out and `memberlistmesh` promoted to primary (following by disabling the deprecated `mesh` gossip once it's defined as secondary)

Unfortunately, this work was never quite completed upstream in kops, it was tracked in https://github.com/kubernetes/kops/issues/7436 for a while but closed without getting completed.

`mesh` gossip presents several challenges when cluster reaches a certain size.

There is a fairly simple procedure for promoting `memberlistmesh` to be the primary gossip, described [here](https://github.com/kubernetes/kops/issues/7436#issuecomment-548104333), unfortunately since the provider doesn't expose the `GossipConfig` & `DNSControllerGossipConfig` blocks in the cluster resource spec we don't have a way to apply this change with the provider.

from a quick look at `gen-tf-code`, it appears that both blocks are excluded: https://github.com/terraform-kops/terraform-provider-kops/blob/14d0485227f4620980c81a8eecda264d2bf6f985/hack/gen-tf-code/main.go#L137

not sure why?

### PR DESCRIPTION
**Pull request by dkulchinsky**
fixes #46

### CODE REVIEW

**Comment by eddycharly** [comment]
This looks good, you probably need to take this into consideration when validating a cluster now :)

**Comment by dkulchinsky** [comment]
> This looks good, you probably need to take this into consideration when validating a cluster now :)

Thanks @eddycharly! can you elaborate on the validation part?

**Comment by eddycharly** [comment]
If i'm not mistaken we are using https://github.com/kubernetes/kops/blob/master/pkg/validation/validate_cluster.go which should already have the gossip validation logic...

Maybe there's nothing else to do 🤔 

I never worked with gossip so i don't know much about it TBH.

**Comment by dkulchinsky** [comment]
ahh, good point! indeed as I recall cluster validation now uses kops native validation

https://github.com/terraform-kops/terraform-provider-kops/commit/3aa08ab2c617cf930098c5fcd7897996efbf7e80

**Comment by dkulchinsky** [comment]
Hey @sl1pm4t 👋🏼 hope you'd have a chance to take a look?

**Review by sl1pm4t — APPROVED** [review]

**Comment by dkulchinsky** [comment]
thanks folks!

**Comment by dkulchinsky** [comment]
@sl1pm4t, @eddycharly 

looking at #33 & #34, I wonder if I should have done the same here? do we need to bump the schema version for the cluster resource & datasource?

**Comment by eddycharly** [comment]
@dkulchinsky iirc you don't need to bump the version if you only add fields 🤷 

did you try your changes ?

**Comment by dkulchinsky** [comment]
> @dkulchinsky iirc you don't need to bump the version if you only add fields 🤷
> 
> did you try your changes ?

not yet, will give it a go next week and report back

**Comment by dkulchinsky** [comment]
@sl1pm4t @eddycharly rolling this out now in our sandbox cluster and looks like it's working as expected 👍🏼 

cluster spec change was applied and control-plane nodes are rolling out now.

for reference, I've added this block to the cluster spec to switch to `memberlist` gossip protocol as primary.

```hcl
  gossip_config {
    protocol = "memberlist"
    listen   = "0.0.0.0:4000"
    secondary {
      protocol = "mesh"
      listen   = "0.0.0.0:3999"
    }
}

  dns_controller_gossip_config {
    protocol = "memberlist"
    listen   = "0.0.0.0:3993"
    seed     = "127.0.0.1:4000"
    secondary {
      protocol = "mesh"
      listen   = "0.0.0.0:3998"
    }
}
```

confirmed that the `dns-controller` picked up the correct settings:
```
Containers:
  dns-controller:
    Args:
      --watch-ingress=false
      --dns=gossip
      --gossip-protocol=memberlist
      --gossip-listen=0.0.0.0:3993
      --gossip-seed=127.0.0.1:4000
      --gossip-protocol-secondary=mesh
      --gossip-listen-secondary=0.0.0.0:3998
      --gossip-seed-secondary=127.0.0.1:4000
      --zone=sbx-awsuse2.k8s.local
      --internal-ipv4
      --zone=*/*
      -v=2
```

also protokube has the correct flags set:
```
/opt/kops/bin/protokube --bootstrap-master-node-labels=true --channels=s3://<bucket>/addons/bootstrap-channel.yaml --cloud=aws --cluster-id=<cluster>.k8s.local --containerized=false --dns-internal-suffix=internal.<cluster>.k8s.local --gossip-listen-secondary=0.0.0.0:3999 --gossip-listen=0.0.0.0:4000 --gossip-protocol-secondary=mesh --gossip-protocol=memberlist --gossip=true --master=true --node-name=<id> --v=4 --zone=sbx-awsuse2.k8s.local
```

**Comment by eddycharly** [comment]
Thanks @dkulchinsky ! That's awesome 🎉

**Comment by dkulchinsky** [comment]
Thanks a lot @eddycharly 😄 

I did hit a snag towards the end of the process and not sure how to tackle it 😬 

I summarized the details in https://github.com/terraform-kops/terraform-provider-kops/issues/68, would appreciate your thoughts/suggestions 🙏🏼

**Pull request merged**
